import Head from "next/head";

export const metadata = {
  title: "Arc Flash Suit | Arc Rated Suit Kit", 
  
  description: "Tarapro electric arc suit is designed to protect workers from the hazards of an arc flash incident & provides a barrier against the intense heat and flames generated by an arc flash",

  keywords: [ "Arc Flash Suit", "Arc Flash Jacket", "Arc Flash Trousers", "Arc Flash Bib Trousers", "Arc Flash Kits", "Arc Flash Suits", "Arc Flash Jackets", "Arc Flash Pants", "Arc Flash Protection Kit", "Electric Arc Flash Protection", "Vallum Jacket", "Vallum Bib-Trousers", "Vallum Hood with Helmet and Visor", ],

  authors: [{ name: "Tarapro" }],

  openGraph: {
    title: "Konfor FR Coverall | Tarapro",
	
    description: "Tarapro electric arc suit is designed to protect workers from the hazards of an arc flash incident & provides a barrier against the intense heat and flames generated by an arc flash",
	
    url: "/fr-clothing/electrical-arc-flash-clothing/vallum-arc-flash-suit",
	
    siteName: "Tarapro",
	
    images: [
      {
        url: "https://taralohia.com/images/banner-one-ipad.webp",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
};

export default function () {
  return (
    <>
		<section className="bannerSection innrbr">
			<div className="container-fluid">
				<div className="row">
				
					<div className="col-md-12 no-pad">
						<div id="myCarousel" className="carousel slide" data-ride="carousel">
							<div className="carousel-inner">
							
								<div className="item active">
									<div className="container">
										<div className="row">
											<div className="col-md-6 col-sm-6">
												<div className="bannrTxtbox mobilebnnr">
													<div className="bannrBox">
														<h1 className="txtbnnr">Vallum 45Cal Arc Flash Suit</h1>
														<h3>Multi Layered Modacrylic Aramid, Multi Fiber Blend, 470gsm, Rip Stop</h3>
														<ul className="">
															<li>Ultimate protection from electric arc flash</li>
															<li>Category 4 product made using inherently FR lightweight material</li>
														</ul>
													</div>
												</div>
												<div className="clearfix"></div>
											</div>
										</div>
									</div>
									<img src="/images/electric-vallum-kit-banner.webp" className="img-responsive visible-lg visible-md" alt="Vallum 45 Cal Arc Flash Suit"/>
									<img src="/images/electric-vallum-kit-banner-ipad.webp" className="img-responsive visible-sm" alt="Vallum 45 Cal Arc Flash Suit"/>
									<img src="/images/electric-vallum-kit-banner-mb.webp" className="img-responsive visible-xs" alt="Vallum 45 Cal Arc Flash Suit"/>
								</div>
							</div>
						</div>
						<div className="clearfix"></div>
					</div>
				</div>
			</div>
		</section>
		
		<section className="innrsctn">
			<div className="container">
				<div className="row">
					<div className="col-md-12">
					
						<nav aria-label="breadcrumb" className="visible-lg visible-md visible-sm">
							<ol className="breadcrumb">
								<li className="breadcrumb-item"><a href="/">Home</a></li>
								<li className="breadcrumb-item"><a href="/fr-clothing">FR Clothing</a></li>
								<li className="breadcrumb-item"><a href="/fr-clothing/electrical-arc-flash-clothing">Electrical FR Clothing</a></li>
								<li className="breadcrumb-item"><a href="/arc-flash-suit">Arc Flash Suit</a></li>
								<li className="breadcrumb-item active" aria-current="page">Vallum 45Cal Arc Flash Suit</li>
							</ol>
						</nav>
						<div className="mbltxtbx">
							
						</div>
					
						<div className="col-md-7 col-sm-6">
							<div className="prdctimgbx">
								<div className="thumBox">
									<img src="/images/norms/atpv-45.svg" className="img-responsive" alt="45 Cal Arc Flash Kit"/>
								</div>
								<img src="/images/product/electrical/vallum/vallum-arc-flash-suit-1.webp" className="img-responsive" alt="Vallum Arc Flash Suit"/>
							</div>
						</div>
						<div className="col-md-5 col-sm-6">
							<div className="prdctcntntfull">
								<ul>
									<li>Stand up collar</li>
									<li>Front closure with zipper and velcro</li>
									<li>Modacrylic rib wristlet</li>
									<li>Easy adjustable shoulder strap</li>
									<li>Adjustable loop on waist and leg</li>
									<li>Bar-tacked at all stress points</li>
								</ul>
								
								<h3 style={{ textAlign: 'left', color: '#f4791f',  marginLeft: '22px',}} > The Arc Flash Kit Includes </h3>
								<ul>
									<li>Vallum Jacket</li>
									<li>Vallum Bib-Trousers</li>
									<li>Vallum Hood with Helmet and Visor</li>
								</ul>
								
								<img src="/images/norms/cat-III.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/ce.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/en-61482-1-2-apc-2.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/astm-f1506.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/astm-f-2621.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/nfpa-70-e-cat-4.svg" className="img-responsive" alt=""/>
								
								<img src="/images/norms/en-13758-2-40+.svg" className="img-responsive" alt=""/>
								
								<div className="clearfix"></div>
							</div>
						</div>
						
						<div className="clearfix"></div>
					</div>
				</div>
			</div>
		</section>
		
		
		<section className="prdctbxdtls">
			<div className="container">
				<div className="row">
					<div className="col-md-12">
						
						<div className="col-md-4 col-sm-6">
							<div className="boxsctn">
								<div className="boxsctnimg">
									<img src="/images/product/electrical/vallum/vallum-arc-flash-suit-2.webp" className="img-responsive" alt="Vallum Arc Flash Suit - Front closure with zipper and velcro"/>
								</div>
								<hr/>
								<h3>Front closure with <br/> zipper and velcro</h3>
							</div>
						</div>
						
						<div className="col-md-4 col-sm-6">
							<div className="boxsctn">
								<div className="boxsctnimg">
									<img src="/images/product/electrical/vallum/vallum-arc-flash-suit-3.webp" className="img-responsive" alt="Vallum Arc Flash Suit - Adjustable waist loop with velcro"/>
								</div>
								<hr/>
								<h3>Adjustable waist loop <br/>with velcro</h3>
							</div>
						</div>
						
						<div className="col-md-4 col-sm-6">
							<div className="boxsctn">
								<div className="boxsctnimg">
									<img src="/images/product/electrical/vallum/vallum-arc-flash-suit-4.webp" className="img-responsive" alt="Vallum Arc Flash Suit - Bottom adjusted with velcro tab"/>
								</div>
								<hr/>
								<h3>Bottom adjusted <br/>with velcro tab</h3>
							</div>
						</div>
						
						<div className="clearfix"></div>
					</div>
				</div>
			</div>
		</section>
		
		
	</>
);
}